- name: Check if calendar-alarms project checkout exists
  ansible.builtin.stat:
    path: "{{ project_root }}"
  register: calendar_alarms_server

- name: Clone sparse checkout if missing
  ansible.builtin.shell: |
    git clone --filter=blob:none --sparse https://github.com/bethesque/calendar-alarms.git "{{ project_root }}"
    git sparse-checkout set server
  args:
    chdir: "{{ project_root | dirname }}"
    creates: "{{ project_root }}"
  when: not calendar_alarms_server.stat.exists

- name: Update existing checkout
  ansible.builtin.shell: |
    git sparse-checkout add server
    git pull
  args:
    chdir: "{{ project_root }}"
    creates: "{{ server_root }}"