- name: Install packages
  apt:
    name:
      - mpd
      - mpc
      - ffmpeg
      - alsa-utils
      - git
      - python3-pip
      - nginx
    state: present
    update_cache: yes
  become: yes

- name: Install project code
  ansible.builtin.import_tasks: codebase.yml
  tags:
    - http
    - codebase
    - sample_rate

- name: Install Snapserver
  ansible.builtin.import_tasks: snapserver_install.yml
  tags:
    - snapserver
  when: snapcast_enabled == true

- name: Configure Snapserver
  ansible.builtin.import_tasks: snapserver_configure.yml
  tags:
    - snapserver
  when: snapcast_enabled == true

- name: Configure Snapserver service
  ansible.builtin.import_tasks: snapserver_service.yml
  tags:
    - snapserver
  when: snapcast_enabled == true

- name: Configure mpd
  ansible.builtin.import_tasks: mpd_configure.yml

- name: Install http service
  ansible.builtin.import_tasks: http.yml
  tags: http

- name: Install calendar alarms daemon service
  ansible.builtin.import_tasks: calendar_alarms_daemon.yml
  tags: calendar_alarms_daemon

- name: Install bash functions
  ansible.builtin.import_tasks: bash_functions.yml
  tags:
    - bash_functions

- name: Test sound
  ansible.builtin.shell: |
    mpc clear
    mpc add /usr/share/sounds/alsa/Front_Center.wav
    mpc volume 50
    mpc play
    sleep 5
    mpc clear
  environment:
    MPD_HOST: "{{ mpd_bind_address }}"
  tags:
    - audio
    - pvt

# - name: End play
#   ansible.builtin.meta: end_play
