- name: Install project code
  ansible.builtin.import_tasks: codebase.yml
  tags: http

# - name: End play
#   ansible.builtin.meta: end_play

- name: Install packages
  apt:
    name:
      - mpd
      - ffmpeg
      - alsa-utils
      - git
    state: present
    update_cache: yes

# MPD FIFO
- name: Ensure FIFO exists
  command: mkfifo {{ mpd_fifo_path }}
  args:
    creates: "{{ mpd_fifo_path }}"

- name: Set FIFO permissions
  file:
    path: "{{ mpd_fifo_path }}"
    owner: "{{ mpd_user }}"
    group: audio
    mode: "0660"


- name: Install Snapserver
  ansible.builtin.import_tasks: snapserver_install.yml

- name: Configure Snapserver
  ansible.builtin.import_tasks: snapserver_configure.yml

- name: Configure Snapserver service
  ansible.builtin.import_tasks: snapserver_service.yml

- name: Configure mpd
  ansible.builtin.import_tasks: mpd_configure.yml

- name: Install http service
  ansible.builtin.import_tasks: http.yml
  tags: http

- name: Add calendar alarms utils file
  ansible.builtin.template:
    src: calendar-alarms-server-utils.sh.j2
    dest: "/home/{{ ansible_user }}/calendar-alarms-server-utils.sh"
    owner: "{{ ansible_user }}"
    mode: "0755"
