- name: Check mpd group membership
  ansible.builtin.command: id -nG mpd
  register: mpd_groups
  changed_when: false

- name: Ensure mpd user is in audio group
  become: true
  ansible.builtin.user:
    name: mpd
    groups: audio
    append: true
  register: mpd_user_update

- name: Reset connection if group membership changed
  ansible.builtin.include_tasks: reset_connection.yaml
  when: mpd_user_update.changed | bool

- name: Ensure mpd runtime directory exists
  file:
    path: /run/mpd
    state: directory
    owner: "{{ mpd_user }}"
    group: audio
    mode: "0755"

- name: Ensure mpd data directory exists
  file:
    path: /var/lib/mpd/
    state: directory
    owner: "{{ mpd_user }}"
    group: audio
    mode: "0755"

- name: Configure MPD
  template:
    src: mpd.conf.j2
    dest: /etc/mpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart mpd
  tags:
    - sample_rate

- name: Ensure mpd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/mpd.service.d
    state: directory
    mode: "0755"
  become: true

- name: Install mpd systemd override
  ansible.builtin.copy:
    dest: /etc/systemd/system/mpd.service.d/override.conf
    mode: "0644"
    content: |
      [Unit]
      Requires=snapserver.service
      After=snapserver.service

  become: true

# Needs both mpd and snapserver installed
# Must restart mpd after this change
- name: Add mpd user to _snapserver group
  ansible.builtin.user:
    name: mpd
    groups: _snapserver
    append: true

- name: Ensure MPD is enabled and running
  systemd:
    name: mpd
    enabled: yes
    daemon_reload: true
    state: restarted
  become: yes
