host_distro: "{{ ansible_facts['distribution_release'] | lower }}"

ca_snapserver_stream_port: 1804
ca_snapserver_tcp_port: 1805
ca_snapserver_http_port: 1880
ca_snapserver_host:  192.168.20.3
ca_snapserver_rpc_url: "http://{{ ca_snapserver_host }}:{{ ca_snapserver_http_port }}/jsonrpc"

ma_snapserver_host:  nas.dixon.net.au
ma_snapserver_control_port: 1780
ma_snapserver_stream_port: 1704

home_assistant_url: http://nas.dixon.net.au:8123

audio_client_http_port: 8082
