mpd_fifo_path: /run/snapserver/snapfifo
mpd_user: mpd
mpd_bind_address: "/run/mpd/socket"
audio_format: "48000:16:2"

music_directory: /var/lib/mpd/music
playlist_directory: /var/lib/mpd/playlists
db_file: /var/lib/mpd/tag_cache
state_file: /var/lib/mpd/state
sticker_file: /var/lib/mpd/sticker.sql
