- name: reload user systemd daemon
  ansible.builtin.command: systemctl --user daemon-reload

- name: restart snapclient
  systemd:
    name: snapclient
    state: restarted

- name: restart audio-client-http.service
  systemd:
    name: audio-client-http
    scope: user
    state: restarted

- name: restart calendar-alarms-snapclient.service
  ansible.builtin.systemd:
    name: calendar-alarms-snapclient.service
    scope: user
    state: restarted
    enabled: true

- name: reload system systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable and start set-amixer-volume service
  become: true
  ansible.builtin.systemd:
    name: set-amixer-volume
    state: started
    enabled: true
