all:
  children:
    audio_host:
      hosts:
        travnas:
          ansible_user: beth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3.13
          ansible_become_pass: "{{ travnas_pass }}"

    audio_clients:
      hosts:
        # These have static IPs and have been added to the /etc/hosts file
        # because using the .local address is unreliable
        officepi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_host_id: officepi
          snapclient_arch: "armhf"
          host_distro: trixie
          snapclient_latency: 0
          is_pi: true
          ansible_become_pass: "{{ pi_pass }}"

        patpi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_host_id: patpi
          snapclient_latency: 0
          is_pi: true
          ansible_become_pass: "{{ pi_pass }}"

        kaypi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_host_id: kaypi
          snapclient_latency: 170
          is_pi: true
          ansible_become_pass: "{{ pi_pass }}"

        ecal.travis.dixon.net.au:
          ansible_user: thetrav
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_host_id: ecal
          snapclient_latency: 0
          is_pi: true

        # travnas:
        #   ansible_user: beth
        #   ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        #   ansible_python_interpreter: /usr/bin/python3.13
        #   snapclient_host_id: travnas
        #   snapclient_latency: 0
        #   is_pi: false
        #   ansible_become_pass: "{{ travnas_pass }}"
