all:
  children:
    audio_host:
      hosts:
        travnas:
          ansible_user: beth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3.13
          ansible_become_pass: "{{ travnas_pass }}"

    audio_clients:
      hosts:
        # These have static IPs and have been added to the /etc/hosts file
        # because using the .local address is unreliable
        officepi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          ca_snapclient_host_id: officepi
          ma_snapclient_host_id: ma_officepi
          snapclient_arch: "armhf"
          host_distro: trixie
          ca_snapclient_latency: 0
          ma_snapclient_latency: 100
          is_pi: true
          ansible_become_pass: "{{ pi_pass }}"

        patpi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          ca_snapclient_host_id: patpi
          ca_snapclient_latency: 0
          ma_snapclient_host_id: ma_patpi
          ma_snapclient_latency: 100
          snapclient_arch: "armhf"
          is_pi: true
          ansible_become_pass: "{{ pi_pass }}"

        kaypi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_arch: "armhf"
          ca_snapclient_host_id: kaypi
          ca_snapclient_latency: 170
          ma_snapclient_host_id: ma_kaypi
          ma_snapclient_latency: 270
          is_pi: true
          ansible_become_pass: "{{ pi_pass }}"

        travcal:
          ansible_user: thetrav
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_arch: "armhf"
          ca_snapclient_host_id: ecal
          ca_snapclient_latency: 0
          ma_snapclient_host_id: ma_ecal
          ma_snapclient_latency: 100
          is_pi: true

        travnas:
          ansible_user: beth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3.13
          ca_snapclient_host_id: travnas
          ca_snapclient_latency: 0
          ma_snapclient_host_id: ma_travnas
          ma_snapclient_latency: 100
          is_pi: false
          ansible_become_pass: "{{ travnas_pass }}"
          project_root: /home/{{ ansible_user }}/calendar-alarms-2
