all:
  children:
    audio_host:
      hosts:
        travnas:
          ansible_user: beth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3.13
          ansible_become_pass: "{{ travnas_pass }}"

    audio_clients:
      hosts:
        # These have static IPs and have been added to the /etc/hosts file
        # because using the .local address is unreliable
        officepi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          ca_snapclient_host_id: officepi
          ma_snapclient_host_id: ma_officepi
          hass_player_entity_id: media_player.officepi_2
          snapclient_arch: "armhf"
          ca_snapclient_latency: 0
          ma_snapclient_latency: 100
          ma_sendspin_initial_delay: 0
          is_pi: true
          is_bluetooth_audio: false
          ansible_become_pass: "{{ pi_pass }}"
          speaker_display_name: Office speaker

        patpi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          ca_snapclient_host_id: patpi
          ca_snapclient_latency: 0
          ma_snapclient_host_id: ma_patpi
          hass_player_entity_id: media_player.patpi_2
          ma_snapclient_latency: 100
          ma_sendspin_initial_delay: 50
          snapclient_arch: "armhf"
          is_pi: true
          is_bluetooth_audio: false
          ansible_become_pass: "{{ pi_pass }}"
          speaker_display_name: Pat's speaker

        kaypi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_arch: "armhf"
          ca_snapclient_host_id: kaypi
          ca_snapclient_latency: 170
          ma_snapclient_host_id: ma_kaypi
          hass_player_entity_id: media_player.kaypi_2
          ma_snapclient_latency: 270
          ma_sendspin_initial_delay: 170
          is_pi: true
          is_bluetooth_audio: false
          ansible_become_pass: "{{ pi_pass }}"
          speaker_display_name: Kay's speaker

        travcal:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          snapclient_arch: "armhf"
          ca_snapclient_host_id: ecal
          ca_snapclient_latency: 0
          ma_snapclient_host_id: ma_ecal
          hass_player_entity_id: media_player.travcal_2
          ma_snapclient_latency: 100
          ma_sendspin_initial_delay: 75
          is_pi: true
          is_bluetooth_audio: false
          ansible_become_pass: "{{ pi_pass }}"
          speaker_display_name: TravCal speaker

        travnas:
          ansible_user: beth
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3.13
          ca_snapclient_host_id: travnas
          ca_snapclient_latency: 0
          ma_snapclient_host_id: ma_travnas
          hass_player_entity_id: media_player.travnas_2
          ma_snapclient_latency: 100
          ma_sendspin_initial_delay: 0
          is_pi: false
          is_bluetooth_audio: false
          ansible_become_pass: "{{ travnas_pass }}"
          project_root: /home/{{ ansible_user }}/calendar-alarms-2
          speaker_display_name: TravNAS speaker

    bluetooth_button_listeners:
      hosts:
        officepi:
          ansible_user: pi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python
          ansible_become_pass: "{{ pi_pass }}"