- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Check if calendar-alarms client checkout exists
  ansible.builtin.stat:
    path: "{{ client_root }}"
  register: calendar_alarms_client

- name: Update existing checkout
  ansible.builtin.command:
    cmd: git pull
    chdir: "{{ project_root }}"
  when: calendar_alarms_client.stat.exists

- name: Clone sparse checkout if missing
  ansible.builtin.shell: |
    git clone --filter=blob:none --sparse https://github.com/bethesque/calendar-alarms.git "{{ project_root }}"
    cd "{{ project_root }}"
    git sparse-checkout set client
  args:
    chdir: "{{ project_root | dirname }}"
    creates: "{{ client_root }}"
  when: not calendar_alarms_client.stat.exists
