# Logs can be viewed with `journalctl SYSLOG_IDENTIFIER=calendar-alarms-http`
- name: Install http service
  ansible.builtin.template:
    src: calendar-alarms-http.service.j2
    dest: "/home/{{ snapclient_user }}/.config/systemd/user/calendar-alarms-http.service"
    owner: "{{ snapclient_user }}"
    group: "{{ snapclient_user }}"
    mode: "0644"

- name: Reload user systemd daemon
  ansible.builtin.command: systemctl --user daemon-reload

- name: Restart http service
  ansible.builtin.systemd:
    name: calendar-alarms-http.service
    scope: user
    state: restarted
    enabled: true
