# - name: End play for host if version matches
#   ansible.builtin.meta: end_play

- name: Configure sound
  ansible.builtin.import_tasks: sound.yml

- name: Configure snapclient_user (the ansible user)
  ansible.builtin.import_tasks: snapclient_user.yml

- name: Install Snapclient
  ansible.builtin.import_tasks: snapclient_install.yml

- name: Configure Snapclient service
  ansible.builtin.import_tasks: snapclient_service.yml

- name: Configure Snapclient Identification service
  ansible.builtin.import_tasks: snapclient_identify.yml

- name: Install alsa-utils
  become: true
  ansible.builtin.package:
    name: alsa-utils
    state: present

- name: Add calendar alarms utils file
  ansible.builtin.template:
    src: calendar-alarms-client-utils.sh.j2
    dest: "/home/{{ snapclient_user }}/calendar-alarms-client-utils.sh"
    owner: "{{ snapclient_user }}"
    group: "{{ snapclient_user }}"
    mode: "0755"

- name: Install HTTP service
  ansible.builtin.import_tasks: http.yml
