#- name: Snapclient service installation
#  ansible.builtin.import_tasks: snapclient.yml
#  tags:
#    - snapclient

- name: Install sendspin-armv6
  ansible.builtin.import_tasks: sendspin.yml
  tags:
    - sendspin
  when: host_distro == "trixie"
