- name: Install sendspin-armv6
  ansible.builtin.import_tasks: sendspin.yml
  tags:
    - sendspin
  when: host_distro == "trixie"

- name: Install bash functions
  ansible.builtin.import_tasks: bash_functions.yml
  tags:
    - bash_functions
