# Relies on the fact that snapclient has already been installed by the calendar alarms project
- name: Find snapclient binary
  ansible.builtin.command: which snapclient
  register: snapclient_which
  changed_when: false
  failed_when: false
  tags:
    - music_assistant_service

- name: Store snapclient path
  ansible.builtin.set_fact:
    snapclient_path: "{{ snapclient_which.stdout }}"
  tags:
    - music_assistant_service

# Logs can be viewed with `journalctl SYSLOG_IDENTIFIER=music-assistant-snapclient`
- name: Install snapclient user service
  ansible.builtin.template:
      # Give it a custom service name so multiple snapclient instances can be run if needed
    # (e.g. one for calendar alarms, one for general music)
    src: music-assistant-snapclient.service.j2
    dest: "/home/{{ snapclient_user }}/.config/systemd/user/music-assistant-snapclient.service"
    owner: "{{ snapclient_user }}"
    group: "{{ snapclient_user }}"
    mode: "0644"
  tags:
    - music_assistant_service

- name: Reload user systemd daemon
  ansible.builtin.command: systemctl --user daemon-reload
  tags:
    - music_assistant_service

#- name: Restart user snapclient service
#  ansible.builtin.systemd:
#    name: music-assistant-snapclient.service
#    scope: user
#    state: restarted
#    enabled: true
#  tags:
#    - music_assistant_service

# DISABLE
- name: Disable Music Assistant snapclient service (using sendspin now)
  ansible.builtin.command: systemctl --user disable music-assistant-snapclient.service
  tags:
    - music_assistant_service
    - disable_music_assistant_service
# DISABLE

- name: Install bash functions
  ansible.builtin.import_tasks: bash_functions.yml
  tags:
    - bash_functions

