- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Check if calendar-alarms client checkout exists
  ansible.builtin.stat:
    path: "{{ project_root }}"
  register: calendar_alarms_client

- name: Clone sparse checkout if missing
  ansible.builtin.shell: |
    git clone --filter=blob:none --sparse https://github.com/bethesque/calendar-alarms.git "{{ project_root }}"
    cd "{{ project_root }}"
    git sparse-checkout set client
  args:
    chdir: "{{ project_root | dirname }}"
    creates: "{{ project_root }}"
  when: not calendar_alarms_client.stat.exists

- name: Update existing checkout
  ansible.builtin.shell: |
    git sparse-checkout add client
    git pull
  args:
    chdir: "{{ project_root }}"


- name: Pip install
  ansible.builtin.shell: |
    {{ ansible_python_interpreter }} -m venv .venv
    source .venv/bin/activate
    .venv/bin/python -m pip install .
  args:
    chdir: "{{ client_root }}"
  tags:
    - slow

- name: Add config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ client_root }}/config.yaml"
    owner: "{{ snapclient_user }}"
    group: "{{ snapclient_user }}"
    mode: "0755"
  tags:
    - config
