# - name: Stop
#   ansible.builtin.meta: end_play

- name: Checkout code
  ansible.builtin.import_tasks: codebase.yml
  tags:
    - codebase
    - http

- name: Install bash functions
  ansible.builtin.import_tasks: bash_functions.yml
  tags:
    - bash_functions

- name: Configure snapclient_user (the ansible user)
  ansible.builtin.import_tasks: snapclient_user.yml
  tags: snapclient

- name: Install Snapclient
  ansible.builtin.import_tasks: snapclient_install.yml
  when: is_pi # Snapcast is custom built on travnas
  tags:
    - snapclient

- name: Configure Calendar Alarms Snapclient service
  ansible.builtin.import_tasks: snapclient_service.yml
  tags:
    - calendar_alarms
    - snapclient
    - snapclient_service

- name: Configure Snapclient Identification service
  ansible.builtin.import_tasks: snapclient_identify.yml
  tags:
    - calendar_alarms
    - snapclient

- name: Install alsa-utils
  become: true
  ansible.builtin.package:
    name: alsa-utils
    state: present

- name: Install HTTP service
  ansible.builtin.import_tasks: http.yml
  tags: http

- name: Check if calendar-alarms-snapclient.service is active
  ansible.builtin.command:
    cmd: systemctl --user is-active calendar-alarms-snapclient.service
  register: script_result
  changed_when: false
  failed_when: "'active' not in script_result.stdout"

- name: Check if audio-client-http.service is active
  ansible.builtin.command:
    cmd: systemctl --user is-active audio-client-http.service
  changed_when: false
  register: script_result
  failed_when: "'active' not in script_result.stdout"
  tags: http

- name: Test audio
  ansible.builtin.shell: |
    amixer set Speaker 10
    speaker-test -c 2 -t wav -l 1
  changed_when: false
  tags: audio
  when: not is_bluetooth_audio

- name: Set default amixer volume
  ansible.builtin.command:
    cmd: "amixer set Speaker {{ default_speaker_volume }}"
  tags:
    - audio
    - default_volume
  when: not is_bluetooth_audio
