# - name: Stop
#   ansible.builtin.meta: end_play

- name: Checkout code
  ansible.builtin.import_tasks: codebase.yml

- name: Configure sound
  ansible.builtin.import_tasks: sound.yml
  when: is_pi

- name: Configure snapclient_user (the ansible user)
  ansible.builtin.import_tasks: snapclient_user.yml
  tags: snapclient

- name: Install Snapclient
  ansible.builtin.import_tasks: snapclient_install.yml
  when: is_pi # Snapcast is custom built on travnas
  tags:
    - snapclient

- name: Configure Calendar Alarms Snapclient service
  ansible.builtin.import_tasks: snapclient_service.yml
  tags:
    - calendar_alarms
    - snapclient
    - snapclient_service

- name: Configure Snapclient Identification service
  ansible.builtin.import_tasks: snapclient_identify.yml
  tags:
    - calendar_alarms
    - snapclient

- name: Install alsa-utils
  become: true
  ansible.builtin.package:
    name: alsa-utils
    state: present

- name: Add calendar alarms utils file
  ansible.builtin.template:
    src: calendar-alarms-client-utils.sh.j2
    dest: "/home/{{ snapclient_user }}/calendar-alarms-client-utils.sh"
    owner: "{{ snapclient_user }}"
    group: "{{ snapclient_user }}"
    mode: "0755"
    tags: calendar_alarms

- name: Install HTTP service
  ansible.builtin.import_tasks: http.yml

- name: Check if calendar-alarms-snapclient.service is active
  ansible.builtin.command:
    cmd: systemctl --user is-active calendar-alarms-snapclient.service
  changed_when: false
  failed_when: false

- name: Check if audio-client-http.service is active
  ansible.builtin.command:
    cmd: systemctl --user is-active audio-client-http.service
  changed_when: false
  failed_when: false
