- name: Stop and disable system-level snapclient service (if it exists)
  become: true
  ansible.builtin.systemd:
    name: snapclient.service
    state: stopped
    enabled: false
  failed_when: false

- name: Find snapclient binary
  ansible.builtin.command: which snapclient
  register: snapclient_which
  changed_when: false
  failed_when: false

- name: Store snapclient path
  ansible.builtin.set_fact:
    snapclient_path: "{{ snapclient_which.stdout }}"

# Configure snapclient systemd service for user
# Best to do it as a user service rather than a system service to avoid permissions
# issues with audio devices. The Bluetooth audio sink is owned by the user,
# so its easiest if the snapclient service runs as the user as well.

# Logs can be viewed with `journalctl SYSLOG_IDENTIFIER=calendar-alarms-snapclient`
- name: Install snapclient user service
  ansible.builtin.template:
      # Give it a custom service name so multiple snapclient instances can be run if needed
    # (e.g. one for calendar alarms, one for general music)
    src: calendar-alarms-snapclient.service.j2
    dest: "/home/{{ snapclient_user }}/.config/systemd/user/calendar-alarms-snapclient.service"
    owner: "{{ snapclient_user }}"
    group: "{{ snapclient_user }}"
    mode: "0644"

- name: Reload user systemd daemon
  ansible.builtin.command: systemctl --user daemon-reload

- name: Restart user snapclient service
  ansible.builtin.systemd:
    name: calendar-alarms-snapclient.service
    scope: user
    state: restarted
    enabled: true

- name: Setup start/stop timers for officepi
  ansible.builtin.import_tasks: snapclient_officepi.yml
  tags:
    - officepi
  when: inventory_hostname == 'officepi'
