- name: Check if calendar-alarms client checkout exists
  ansible.builtin.stat:
    path: "{{ project_root }}"
  register: calendar_alarms_client

- name: Clone sparse checkout if missing
  ansible.builtin.shell: |
    git clone --filter=blob:none --sparse https://github.com/bethesque/calendar-alarms.git "{{ project_root }}"
    cd "{{ project_root }}"
    git sparse-checkout set bluetooth-button-listener
  args:
    chdir: "{{ project_root | dirname }}"
    creates: "{{ project_root }}"
  when: not calendar_alarms_client.stat.exists

- name: Update existing checkout
  ansible.builtin.shell: |
    git sparse-checkout add bluetooth-button-listener
    git pull
  args:
    chdir: "{{ project_root }}"

- name: Add .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ bbl_root }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
