- name: Add .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ bbl_root }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  tags:
    - env
  notify:
    - restart bluetooth-button-listener.service

# Logs can be viewed with `journalctl SYSLOG_IDENTIFIER=bluetooth-button-listener`
- name: Install service
  ansible.builtin.template:
    src: bluetooth-button-listener.service.j2
    dest: "/home/{{ ansible_user }}/.config/systemd/user/bluetooth-button-listener.service"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify:
    - reload user systemd daemon
